import profile from "../../../assets/profile.jpg";

const mentors = [
  {
    id: 1,
    avatar: profile,
    name: "Dr. Arjun Mehta",
    email: "arjun.mehta@christuniversity.in",
    department: "Computer Science & Engineering",
    designation: "Associate Professor",
    studentsAssigned: 24,
    totalStudents: 30,
    meetings: 18,
    attendance: 92,
    status: "Active",
  },
  {
    id: 2,
    avatar: profile,
    name: "Dr. Neha Sharma",
    email: "neha.sharma@christuniversity.in",
    department: "Computer Science & Engineering",
    designation: "Associate Professor",
    studentsAssigned: 22,
    totalStudents: 30,
    meetings: 16,
    attendance: 90,
    status: "Active",
  },
  {
    id: 3,
    avatar: profile,
    name: "Prof. Vivek Singh",
    email: "vivek.singh@christuniversity.in",
    department: "Computer Science & Engineering",
    designation: "Assistant Professor",
    studentsAssigned: 21,
    totalStudents: 30,
    meetings: 14,
    attendance: 88,
    status: "Active",
  },
  {
    id: 4,
    avatar: profile,
    name: "Dr. Meera Reddy",
    email: "meera.reddy@christuniversity.in",
    department: "Information Science & Engineering",
    designation: "Associate Professor",
    studentsAssigned: 20,
    totalStudents: 30,
    meetings: 13,
    attendance: 93,
    status: "Active",
  },
  {
    id: 5,
    avatar: profile,
    name: "Dr. Karan Patel",
    email: "karan.patel@christuniversity.in",
    department: "Computer Science & Engineering",
    designation: "Assistant Professor",
    studentsAssigned: 19,
    totalStudents: 30,
    meetings: 12,
    attendance: 89,
    status: "Active",
  },
  {
    id: 6,
    avatar: profile,
    name: "Dr. Priya Nair",
    email: "priya.nair@christuniversity.in",
    department: "Artificial Intelligence & ML",
    designation: "Associate Professor",
    studentsAssigned: 18,
    totalStudents: 30,
    meetings: 11,
    attendance: 87,
    status: "Busy",
  },
  {
    id: 7,
    avatar: profile,
    name: "Prof. Rohan Verma",
    email: "rohan.verma@christuniversity.in",
    department: "Data Science",
    designation: "Assistant Professor",
    studentsAssigned: 16,
    totalStudents: 30,
    meetings: 9,
    attendance: 85,
    status: "On Leave",
  },
  {
    id: 8,
    avatar: profile,
    name: "Dr. Ananya Iyer",
    email: "ananya.iyer@christuniversity.in",
    department: "Electronics & Communication",
    designation: "Assistant Professor",
    studentsAssigned: 15,
    totalStudents: 30,
    meetings: 8,
    attendance: 83,
    status: "Inactive",
  },
];

export default mentors;