const studentData = [
  {
    id: 1,
    rollNo: "22CS001",
    name: "Rahul Sharma",
    email: "rahul.sharma@college.edu",
    year: "2nd Year",
    section: "A",
    attendance: "94%",
    cgpa: "9.12",
    status: "Active",
  },
  {
    id: 2,
    rollNo: "22CS002",
    name: "Priya Verma",
    email: "priya.verma@college.edu",
    year: "2nd Year",
    section: "A",
    attendance: "91%",
    cgpa: "8.87",
    status: "Active",
  },
  {
    id: 3,
    rollNo: "22CS003",
    name: "Amit Kumar",
    email: "amit.kumar@college.edu",
    year: "2nd Year",
    section: "A",
    attendance: "88%",
    cgpa: "8.46",
    status: "Warning",
  },
  {
    id: 4,
    rollNo: "22CS004",
    name: "Sneha Reddy",
    email: "sneha.reddy@college.edu",
    year: "2nd Year",
    section: "A",
    attendance: "97%",
    cgpa: "9.58",
    status: "Active",
  },
  {
    id: 5,
    rollNo: "22CS005",
    name: "Arjun Patel",
    email: "arjun.patel@college.edu",
    year: "2nd Year",
    section: "A",
    attendance: "82%",
    cgpa: "7.95",
    status: "Warning",
  },
  {
    id: 6,
    rollNo: "22CS006",
    name: "Neha Gupta",
    email: "neha.gupta@college.edu",
    year: "2nd Year",
    section: "A",
    attendance: "95%",
    cgpa: "9.34",
    status: "Active",
  },
  {
    id: 7,
    rollNo: "22CS007",
    name: "Karan Singh",
    email: "karan.singh@college.edu",
    year: "2nd Year",
    section: "A",
    attendance: "90%",
    cgpa: "8.74",
    status: "Active",
  },
  {
    id: 8,
    rollNo: "22CS008",
    name: "Ananya Rao",
    email: "ananya.rao@college.edu",
    year: "2nd Year",
    section: "A",
    attendance: "98%",
    cgpa: "9.81",
    status: "Active",
  },
];

export default studentData;