const studentsData = [
  {
    id: 1,
    name: "John Anderson",
    regNo: "22BCA1023",
    department: "Computer Applications",
    course: "BCA",
    semester: "Semester V",
    attendance: 92,
    cgpa: 8.76,
    meetings: 12,
    lastMeeting: "12 Jul 2026",
    status: "Good Standing",
    email: "john.anderson@christuniversity.in",
    phone: "+91 9876543210",
    city: "Bengaluru",
    avatar: "https://i.pravatar.cc/150?img=12",
  },
  {
    id: 2,
    name: "Emily Watson",
    regNo: "22BCA1041",
    department: "Computer Applications",
    course: "BCA",
    semester: "Semester V",
    attendance: 88,
    cgpa: 8.42,
    meetings: 10,
    lastMeeting: "10 Jul 2026",
    status: "Excellent",
    email: "emily.watson@christuniversity.in",
    phone: "+91 9876543211",
    city: "Bengaluru",
    avatar: "https://i.pravatar.cc/150?img=32",
  },
  {
    id: 3,
    name: "David Miller",
    regNo: "22BCA1056",
    department: "Computer Applications",
    course: "BCA",
    semester: "Semester V",
    attendance: 81,
    cgpa: 7.98,
    meetings: 9,
    lastMeeting: "08 Jul 2026",
    status: "Needs Attention",
    email: "david.miller@christuniversity.in",
    phone: "+91 9876543212",
    city: "Bengaluru",
    avatar: "https://i.pravatar.cc/150?img=14",
  },
  {
    id: 4,
    name: "Sophia Wilson",
    regNo: "22BCA1072",
    department: "Computer Applications",
    course: "BCA",
    semester: "Semester V",
    attendance: 95,
    cgpa: 9.18,
    meetings: 14,
    lastMeeting: "11 Jul 2026",
    status: "Excellent",
    email: "sophia.wilson@christuniversity.in",
    phone: "+91 9876543213",
    city: "Bengaluru",
    avatar: "https://i.pravatar.cc/150?img=44",
  },
  {
    id: 5,
    name: "Ryan Thomas",
    regNo: "22BCA1085",
    department: "Computer Applications",
    course: "BCA",
    semester: "Semester V",
    attendance: 84,
    cgpa: 8.05,
    meetings: 8,
    lastMeeting: "06 Jul 2026",
    status: "Good Standing",
    email: "ryan.thomas@christuniversity.in",
    phone: "+91 9876543214",
    city: "Bengaluru",
    avatar: "https://i.pravatar.cc/150?img=18",
  },
  {
    id: 6,
    name: "Olivia Brown",
    regNo: "22BCA1091",
    department: "Computer Applications",
    course: "BCA",
    semester: "Semester V",
    attendance: 91,
    cgpa: 8.74,
    meetings: 13,
    lastMeeting: "09 Jul 2026",
    status: "Excellent",
    email: "olivia.brown@christuniversity.in",
    phone: "+91 9876543215",
    city: "Bengaluru",
    avatar: "https://i.pravatar.cc/150?img=47",
  },
  {
    id: 7,
    name: "Daniel Clark",
    regNo: "22BCA1104",
    department: "Computer Applications",
    course: "BCA",
    semester: "Semester V",
    attendance: 79,
    cgpa: 7.56,
    meetings: 7,
    lastMeeting: "05 Jul 2026",
    status: "Needs Attention",
    email: "daniel.clark@christuniversity.in",
    phone: "+91 9876543216",
    city: "Bengaluru",
    avatar: "https://i.pravatar.cc/150?img=23",
  },
  {
    id: 8,
    name: "Grace Lee",
    regNo: "22BCA1110",
    department: "Computer Applications",
    course: "BCA",
    semester: "Semester V",
    attendance: 94,
    cgpa: 9.02,
    meetings: 15,
    lastMeeting: "13 Jul 2026",
    status: "Excellent",
    email: "grace.lee@christuniversity.in",
    phone: "+91 9876543217",
    city: "Bengaluru",
    avatar: "https://i.pravatar.cc/150?img=48",
  },
];

export default studentsData;