export const students = [
  {
    id: 1,
    name: "Rahul Sharma",
    email: "rahul.sharma@christuniversity.in",
    usn: "23CS001",
    department: "Computer Science",
    year: "4th",
    section: "A",
    semester: "8",
    status: "Unassigned",
  },
  {
    id: 2,
    name: "Priya Nair",
    email: "priya.nair@christuniversity.in",
    usn: "23CS002",
    department: "Computer Science",
    year: "4th",
    section: "A",
    semester: "8",
    status: "Unassigned",
  },
  {
    id: 3,
    name: "Arjun Mehta",
    email: "arjun.mehta@christuniversity.in",
    usn: "23CS003",
    department: "Computer Science",
    year: "3rd",
    section: "B",
    semester: "6",
    status: "Unassigned",
  },
  {
    id: 4,
    name: "Sneha Reddy",
    email: "sneha.reddy@christuniversity.in",
    usn: "23CS004",
    department: "Computer Science",
    year: "3rd",
    section: "A",
    semester: "6",
    status: "Unassigned",
  },
  {
    id: 5,
    name: "Vikram Rao",
    email: "vikram.rao@christuniversity.in",
    usn: "23CS005",
    department: "Computer Science",
    year: "2nd",
    section: "B",
    semester: "4",
    status: "Unassigned",
  },
  {
    id: 6,
    name: "Meghana Shetty",
    email: "meghana.shetty@christuniversity.in",
    usn: "23CS006",
    department: "Computer Science",
    year: "2nd",
    section: "A",
    semester: "4",
    status: "Unassigned",
  },
  {
    id: 7,
    name: "Aisha Khan",
    email: "aisha.khan@christuniversity.in",
    usn: "23CS007",
    department: "Computer Science",
    year: "1st",
    section: "A",
    semester: "2",
    status: "Unassigned",
  },
  {
    id: 8,
    name: "Kiran Kumar",
    email: "kiran.kumar@christuniversity.in",
    usn: "23CS008",
    department: "Computer Science",
    year: "1st",
    section: "B",
    semester: "2",
    status: "Unassigned",
  },
];

export const mentors = [
  {
    id: 1,
    name: "Dr. Arjun Mehta",
    department: "Computer Science",
    assigned: 24,
    capacity: 30,
  },
  {
    id: 2,
    name: "Dr. Priya Sharma",
    department: "Computer Science",
    assigned: 18,
    capacity: 30,
  },
  {
    id: 3,
    name: "Dr. Vivek Rao",
    department: "Computer Science",
    assigned: 27,
    capacity: 30,
  },
  {
    id: 4,
    name: "Dr. Meera Thomas",
    department: "Computer Science",
    assigned: 15,
    capacity: 30,
  },
  {
    id: 5,
    name: "Dr. Kiran Nair",
    department: "Computer Science",
    assigned: 22,
    capacity: 30,
  },
  {
    id: 6,
    name: "Dr. Ashwin Kumar",
    department: "Computer Science",
    assigned: 29,
    capacity: 30,
  },
];